Makefile protection around configure.mk

diff --git a/c/Makefile b/c/Makefile
--- a/c/Makefile
+++ b/c/Makefile
@@ -1,6 +1,23 @@
-CC=gcc
-CCFLAGS=-Wall -O2
+# This won't fail if it doesn't exist, but it will be auto-created.
+-include configure.mk
+
+#############################################################################
+# Hopefully these have been set in configure.mk, if not
+# the defaults will catch.
+#############################################################################
+CC:=gcc
+CCFLAGS:=-Wall -O2
+
+## DEFAULTS WON'T INSTALL, set in configure.mk
+prefix:=
+bindir:=bin
+DESTDIR:=
+#############################################################################
+
+
+# This will always be added to CCFLAGS, because of the standard for this code.
 CCFLAGS+=-std=gnu99
+# These are DEF options that will be additive to CCFLAGS
 ifdef MAC_BROKEN_BASH
 CCFLAGS+=-DMAC_BROKEN_BASH
 endif
@@ -8,27 +25,37 @@ ifdef DEBUG
 	# Maintainer stuff only, you don't want to see this.
 CCFLAGS+=-ggdb -DDEBUG
 endif
-#CCFLAGS+=-ggdb
 
-## NO DEFAULT PREFIX (not even /)
-prefix:=
 exec_prefix:=$(prefix)
-sbindir:=sbin/
-DESTDIR:=
-INSTALLDIR:=$(DESTDIR)$(exec_prefix)$(sbindir)
+_INSTALLDIR=$(DESTDIR)/$(exec_prefix)/$(bindir)/
+INSTALLDIR=$(shell echo "$(_INSTALLDIR)" | sed -e 's@//*@/@g')
 
 FINAL=echo
 SOURCE=echo.c
-X_DEPS=Makefile
+X_DEPS=Makefile configure.mk
 
+# Linux or Darwin (probably), Darwin is the one I treat differently
 SYS=$(shell uname -s)
+# x86_64 or arm64
 ARCH=$(shell uname -m)
 MAJ_VER=$(shell uname -r | awk -F. '{print $$1}')
-# OS X 11, Big Sur, is the earliest macOS that supported arm64
-TARGET_ARM64=-target arm64-apple-macos11
-# OS X 10.10 is Yosemite, released 2014, which supports
-# all hardware from 2010 or more recent.
-TARGET_X86_64=-target x86_64-apple-macos10.10
+
+BUILD_DIR=$(ARCH).OBJ
+OBJS := $(foreach TT,$(SOURCE),$(patsubst %.c,$(BUILD_DIR)/%.o,$(TT) ) )
+
+ifeq ($(SYS), Darwin)
+ifdef SIGNID
+X_DEPS+=keychain-unlock
+else
+X_DEPS+=no-keychain
+endif
+endif
+
+ifeq ($(shell test "arm64" = $(ARCH); echo $$?), 0)
+ALT_ARCH=x86_64
+else
+ALT_ARCH=arm64
+endif
 
 ifeq ($(shell test "Darwin" = $(SYS) -a $(MAJ_VER) -ge 20; echo $$?), 0)
 # This is a mac running Big Sur (11, D20) or NEWER:
@@ -36,48 +63,165 @@ ifeq ($(shell test "Darwin" = $(SYS) -a $(MAJ_VER) -ge 20; echo $$?), 0)
 # Any build platform here (x86_64 or arm64) will be able to target
 # a universal binary with arm64-Big Sur and x86_64-Yosemite.
 INTERIM=universal.$(FINAL)
+ALT_BUILD_DIR=$(ALT_ARCH).OBJ
+ALT_OBJS := $(foreach TT,$(SOURCE),$(patsubst %.c,$(ALT_BUILD_DIR)/%.o,$(TT) ) )
+# OS X 11, Big Sur, is the earliest macOS that supported arm64
+TARGET_ARM64=-target arm64-apple-macos11
+# OS X 10.10 is Yosemite, released 2014, which supports
+# all hardware from 2010 or more recent.
+TARGET_X86_64=-target x86_64-apple-macos10.10
 else ifeq ($(shell test "Darwin" = $(SYS) -a $(MAJ_VER) -lt 14; echo $$?), 0)
 # This is a mac running Mavericks (10.9, D13) or OLDER.
 # Treating this the same as Linux, where we have no -target specified
 # and just expect the compiler will do the right thing.
-INTERIM=default.$(FINAL)
+INTERIM=$(ARCH).$(FINAL)
 else ifeq ($(shell test "Darwin" = $(SYS); echo $$?), 0)
 # This is a macOS between Yosemite (10.10, D14) and Catalina (10.15, D19)
 # Yosemite is the earliest target macOS I own (or have access to),
 INTERIM=$(ARCH).$(FINAL)
+# OS X 11, Big Sur, is the earliest macOS that supported arm64
+TARGET_ARM64=-target arm64-apple-macos11
+# OS X 10.10 is Yosemite, released 2014, which supports
+# all hardware from 2010 or more recent.
+TARGET_X86_64=-target x86_64-apple-macos10.10
 else
-INTERIM=default.$(FINAL)
+INTERIM=$(ARCH).$(FINAL)
 endif
 
 $(FINAL): $(INTERIM)
+ifeq ($(shell test "Darwin" = "$(SYS)"; echo $$?), 0)
+	@if [ -x "/usr/bin/codesign" -a -x "/usr/bin/security" -a -n "$(SIGNID)" ]; \
+		then \
+			if [ -n "$(CHAIN)" ]; \
+			then \
+				echo "codesign -s \"$(SIGNID)\" --keychain \"$(CHAIN)\" $(INTERIM)"; \
+				/usr/bin/codesign -s "$(SIGNID)" --keychain "$(CHAIN)" $(INTERIM); \
+			else \
+				echo "codesign -s \"$(SIGNID)\" $(INTERIM)"; \
+				/usr/bin/codesign -s "$(SIGNID)" $(INTERIM); \
+			fi; \
+		fi
+endif
+	@echo "    # Copy intermediate target to final $(FINAL)"
 	cp $(INTERIM) $(FINAL)
 
 universal.$(FINAL): x86_64.$(FINAL) arm64.$(FINAL)
+	@echo "    # Darwin specific: join builds into universal.$(FINAL)"
 	lipo -create -output universal.$(FINAL) x86_64.$(FINAL) arm64.$(FINAL)
 
-# x86_64 target is Yosemite (10.10, D14)
-# Yosemite is the earliest target macOS I own (or have access to),
-# You might have luck targeting something that's older, but I
-# won't release what I cannot test.
-# So that's where I'm pegging x86_64 specific targets.
-# There's a comment at the end of the file for further info...
-x86_64.$(FINAL): $(SOURCE) $(X_DEPS)
-	$(CC) $(CCFLAGS) -o x86_64.$(FINAL) $(SOURCE) $(TARGET_X86_64)
+# Make sure to accomodate any ARCH, plus the Darwin targets...
+$(ARCH).$(FINAL): $(OBJS)
+	@echo "    # Linking $@ in `dirname $@` from $(OBJS)"
+ifeq ($(shell test "Darwin" = "$(SYS)" -a "x86_64" = "$(ARCH)"; echo $$?), 0)
+	$(CC) $(TARGET_X86_64) -o $@ $(OBJS)
+else ifeq ($(shell test "Darwin" = "$(SYS)"; echo $$?), 0)
+	$(CC) $(TARGET_ARM64) -o $@ $(OBJS)
+else
+	$(CC) -o $@ $(OBJS)
+endif
 
-# OS X 11, Big Sur is the first arm64 capable version, so it is the lowest
-# target possible for arm64.
-arm64.$(FINAL): $(SOURCE) $(X_DEPS)
-	$(CC) $(CCFLAGS) -o arm64.$(FINAL) $(SOURCE) $(TARGET_ARM64)
+$(ALT_ARCH).$(FINAL): $(ALT_OBJS)
+	@echo "    # Linking $@ in `dirname $@` from $(ALT_OBJS)"
+ifeq ($(shell test "Darwin" = "$(SYS)" -a "x86_64" = "$(ALT_ARCH)"; echo $$?), 0)
+	$(CC) $(TARGET_X86_64) -o $@ $(ALT_OBJS)
+else ifeq ($(shell test "Darwin" = "$(SYS)"; echo $$?), 0)
+	$(CC) $(TARGET_ARM64) -o $@ $(ALT_OBJS)
+else
+	$(CC) -o $@ $(ALT_OBJS)
+endif
 
-default.$(FINAL): $(SOURCE) $(X_DEPS)
-	$(CC) $(CCFLAGS) -o default.$(FINAL) $(SOURCE)
+$(OBJS): $(BUILD_DIR)/%.o: %.c $(X_DEPS)
+	@echo "    # Compiling $@ in `dirname $@` from $<"
+	@echo "    # X_DEPS is $(X_DEPS)"
+	@if [ ! -d "`dirname $@`" ]; \
+		then echo "        # mkdir `dirname $@`";\
+		mkdir `dirname $@`; fi
+ifeq ($(shell test "Darwin" = "$(SYS)" -a "x86_64" = "$(ARCH)"; echo $$?), 0)
+	$(CC) $(CCFLAGS) $(TARGET_X86_64) -c $< -o $@
+else ifeq ($(shell test "Darwin" = "$(SYS)"; echo $$?), 0)
+	$(CC) $(CCFLAGS) $(TARGET_ARM64) -c $< -o $@
+else
+	$(CC) $(CCFLAGS) -c $< -o $@
+endif
+
+$(ALT_OBJS): $(ALT_BUILD_DIR)/%.o: %.c $(X_DEPS)
+	@echo "    # Compiling $@ in `dirname $@` from $< -- Cross Compile $(ALT_ARCH)"
+	@echo "    # X_DEPS is $(X_DEPS)"
+	@if [ ! -d "`dirname $@`" ]; \
+		then echo "        # mkdir `dirname $@`";\
+		mkdir `dirname $@`; fi
+ifeq ($(shell test "Darwin" = "$(SYS)" -a "x86_64" = "$(ALT_ARCH)"; echo $$?), 0)
+	$(CC) $(CCFLAGS) $(TARGET_X86_64) -c $< -o $@
+else ifeq ($(shell test "Darwin" = "$(SYS)"; echo $$?), 0)
+	$(CC) $(CCFLAGS) $(TARGET_ARM64) -c $< -o $@
+else
+	$(CC) $(CCFLAGS) -c $< -o $@
+endif
+
+
+configure.mk: configure.dist
+	@if [ -e "$@" ]; then \
+		echo "##############################################################"; \
+		echo "##  $@ is older than configure.dist!"; \
+		echo "##    Compare them to check for new settings, and save"; \
+		echo "##############################################################"; \
+		false; \
+	else \
+		cp $< $@; \
+	fi
+
+no-keychain:
+	-@if [ -e ./.keychain-unlock ]; then rm ./.keychain-unlock; fi
+	@echo "####################################################################"
+	@echo "#### macOS, SIGNID not set, will not attempt to codesign $(FINAL)"
+	@echo "####################################################################"
+
+keychain-unlock: macos-keychain-unlock
+	@echo "running script macos-keychain-unlock (SIGNID is set)"
+	@./macos-keychain-unlock
+
+macos-keychain-unlock: mk.skel
+	@printf '#!/bin/bash\n' > macos-keychain-unlock
+	@printf '\n_NEED_UNLOCK=1\n' >> macos-keychain-unlock
+	@printf 'CK=`date -v-3m +"%%s"`\n' >> macos-keychain-unlock
+	@printf 'if [ -e './.keychain-unlock' ]\n' >> macos-keychain-unlock
+	@printf 'then\n' >> macos-keychain-unlock
+	@printf '    TS=`stat -f"%%m" ./.keychain-unlock`\n' >> macos-keychain-unlock
+	@printf '    if [ "$$TS" -gt "$$CK" ]\n' >> macos-keychain-unlock
+	@printf '    then\n' >> macos-keychain-unlock
+	@printf '       _NEED_UNLOCK=0\n' >> macos-keychain-unlock
+	@printf '    fi\n' >> macos-keychain-unlock
+	@printf 'fi\n' >> macos-keychain-unlock
+	@printf 'if [ 1 = "$$_NEED_UNLOCK" ]\n' >> macos-keychain-unlock
+	@printf 'then\n' >> macos-keychain-unlock
+ifdef CHAIN
+	@printf "        echo 'security unlock-keychain \"$(CHAIN)\" && touch ./.keychain-unlock'\n" >> macos-keychain-unlock
+	@printf '        security unlock-keychain "$(CHAIN)" && touch ./.keychain-unlock\n' >> macos-keychain-unlock
+else
+	@printf "        echo 'security unlock-keychain && touch ./.keychain-unlock'\n" >> macos-keychain-unlock
+	@printf '        security unlock-keychain && touch ./.keychain-unlock\n' >> macos-keychain-unlock
+endif
+	@printf 'fi\n' >> macos-keychain-unlock
+	@echo "built $@"
+	chmod a+x macos-keychain-unlock
+
 
 install: $(FINAL)
-	@if [ "sbin/" = "$(INSTALLDIR)" ]; then \
+	@if [ "/$(bindir)/" = "$(INSTALLDIR)" ]; then \
 		echo "Cannot install, prefix= and DESTDIR=, both empty." ; \
 		echo "TRY: $$ make INSTALLDIR=<path> install" ; \
 		false; \
-	elif [ -d "$(INSTALLDIR)" ]; then \
+	elif [ "/sbin/" = "$(INSTALLDIR)" ]; then \
+		echo "Cannot install, prefix= and DESTDIR=, both empty." ; \
+		echo "TRY: $$ make INSTALLDIR=<path> install" ; \
+		false; \
+	fi
+	elif [ "/bin/" = "$(INSTALLDIR)" ]; then \
+		echo "Cannot install, prefix= and DESTDIR=, both empty." ; \
+		echo "TRY: $$ make INSTALLDIR=<path> install" ; \
+		false; \
+	fi
+	@if [ -d "$(INSTALLDIR)" ]; then \
 		echo "install -m 775 -C $(FINAL) $(INSTALLDIR)"; \
 		install -m 775 -C $(FINAL) $(INSTALLDIR); \
 	else \
@@ -88,8 +232,20 @@ install: $(FINAL)
 clean:
 	-rm -f $(FINAL).o $(FINAL)*.obj *.$(FINAL)
 
-dist-clean: clean
+dist-clean distclean: clean
 	-rm -f $(FINAL)
+	@if [ -e "configure.mk" ]; then \
+		diff "configure.mk" "configure.dist" 2>&1 >/dev/null; \
+		if [ "$?" != "0" ]; then \
+			echo "##############################################################"; \
+			echo "#### Modified configure.mk exists, remove manually..."; \
+			echo "#### rm configure.mk"; \
+			echo "##############################################################"; \
+			false; \
+		else \
+			rm "configure.mk"; \
+		fi \
+	fi
 
 # FROM WIKIPEDIA...
 #
@@ -126,4 +282,5 @@ dist-clean: clean
 # Real talk... All Apple hardware sold from 2010 on supports Yosemite
 # or newer.  That's 13 years ago, which is forever for Apple hardware.
 #
+# vim: ft=make
 # EOF Makefile
